services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solaceassignment
    volumes:
      # https://github.com/docker-library/postgres/issues/37#issuecomment-3476426533
      - psql:/var/lib/postgresql
    ports:
      - 5432:5432
volumes:
  psql:
